export enum Sistema {
    /* SI_MERCADINHO = 'SI_MERCADINHO',
    SI_CONFECCAO = 'SI_CONFECCAO',
    SI_FACCAO = 'SI_FACCAO',
    SI_REPRESENTACAO = 'SI_REPRESENTACAO',
    SI_REVENDEDORA = 'SI_REVENDEDORA',
    SI_OFICINA = 'SI_OFICINA',
    SI_AUTOPECAS = 'SI_AUTOPECAS',
    SI_FARMACIA = 'SI_FARMACIA',
    SI_PADARIA = 'SI_PADARIA',
    SI_CLINICA = 'SI_CLINICA',
    SI_LOCADORA = 'SI_LOCADORA',
    SI_ESCOLA = 'SI_ESCOLA' */

    SI_MERCADINHO,
    SI_CONFECCAO,
    SI_FACCAO,
    SI_REPRESENTACAO,
    SI_REVENDEDORA,
    SI_OFICINA,
    SI_AUTOPECAS,
    SI_FARMACIA,
    SI_PADARIA,
    SI_CLINICA,
    SI_LOCADORA,
    SI_ESCOLA
}
